#!/bin/bash

STATUS=$(git status --porcelain | grep -E 'README.tpl|MakeFile|Dockefile')
set -e
if [ -n "$STATUS" ]
then
    echo "Updating README.md" && make release 2>&1 > /dev/null
    git add README.md
fi
